server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: clientes
          uri: http://msclientes:8081
          predicates:
            - Path=/clientes/**
        - id: produtos
          uri: http://msprodutos:8082
          predicates:
            - Path=/produtos/**
        - id: cargaprodutos
          uri: http://mscargaprodutos:8083
          predicates:
            - Path=/carga/**
        - id: pedidos
          uri: http://mspedidos:8084
          predicates:
            - Path=/pedidos/**
        - id: logistica-endereco
          uri: http://mslogistica:8085
          predicates:
            - Path=/buscarenderecos/**
        - id: logistica-processar-pedido
          uri: http://mslogistica:8085
          predicates:
            - Path=/logistica/processar/pedido/**
        - id: logistica-buscarEntregasId
          uri: http://mslogistica:8085
          predicates:
            - Path=/buscarEntregasId/**
        - id: logistica-buscarEntregas
          uri: http://mslogistica:8085
          predicates:
            - Path=/buscarEntregas/**
        - id: logistica-atualizarEntrega
          uri: http://mslogistica:8085
          predicates:
            - Path=/atualizarEntrega/**
        - id: logistica-buscarEntregador
          uri: http://mslogistica:8085
          predicates:
            - Path=/buscarEntregador/**
        - id: logistica-criarEntregador
          uri: http://mslogistica:8085
          predicates:
            - Path=/criarEntregador/**
        - id: logistica-encerrarEntrega
          uri: http://mslogistica:8085
          predicates:
            - Path=/encerrarEntrega

logging:
  level:
    org.springframework.cloud.gateway: DEBUG