server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: clientes
          uri: http://localhost:8081
          predicates:
            - Path=/clientes/**
        - id: produtos
          uri: http://localhost:8082
          predicates:
            - Path=/produtos/**
        - id: cargaprodutos
          uri: http://localhost:8083
          predicates:
            - Path=/carga/**
        - id: pedidos
          uri: http://localhost:8084
          predicates:
            - Path=/pedidos/**
        - id: logistica-endereco
          uri: http://localhost:8085
          predicates:
            - Path=/buscarenderecos/**
        - id: logistica-processar-pedido
          uri: http://localhost:8085
          predicates:
            - Path=/logistica/processar/pedido/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG